import os
import sys
import joblib
import pandas as pd
import warnings
import shap
import numpy as np

# Suppress sklearn warnings about feature names
warnings.filterwarnings("ignore", category=UserWarning)

# Add parent to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from preprocessing.pipeline import create_features
from rules.engine import evaluate_rules
from inference.ensemble import combine_scores
from inference.explainer import generate_explanation
from utils.drift_monitor import log_prediction_distribution

MODELS_DIR = os.path.join(os.path.dirname(__file__), "..", "models")

# Lazy loading of models to speed up startup, but for a real engine we cache them in memory
_MODELS = {}

def load_models():
    """Loads all models from the model registry into memory."""
    if _MODELS: return
    
    models_to_load = [
        ("payment", "payment_model.pkl"),
        ("anomaly", "anomaly_model.pkl"),
        ("account", "account_model.pkl"),
        ("refund", "refund_model.pkl"),
        ("bot", "bot_model.pkl")
    ]
    
    for key, filename in models_to_load:
        path = os.path.join(MODELS_DIR, filename)
        if os.path.exists(path):
            _MODELS[key] = joblib.load(path)
        else:
            print(f"Warning: {filename} not found.")

def determine_fraud_type(transaction: dict, models_loaded: dict) -> str:
    """
    In a real system, the event type determines which model to route to.
    For this engine, we'll infer it based on context or default to payment.
    """
    event_type = transaction.get("event_type", "payment")
    if event_type in ["login", "account_creation"]: return "account"
    if event_type == "refund_request": return "refund"
    if event_type == "api_request": return "bot"
    return "payment"

def predict_transaction(event_data: dict) -> dict:
    """
    The Central Fraud Intelligence Engine Entrypoint.
    
    Input: event_data (dict)
    Output: dict with fraud_probability, risk_score, risk_level, fraud_type, reasons
    """
    load_models()
    
    fraud_type = determine_fraud_type(event_data, _MODELS)
    
    # 1. Preprocess & Feature Engineering
    # Convert single event to DataFrame
    df_raw = pd.DataFrame([event_data])
    
    # In a real system, historical data is needed for velocity.
    # Here create_features handles single row (though velocity will be 0)
    df_processed = create_features(df_raw)
    
    # Fill any NaNs generated by feature pipeline
    df_processed = df_processed.fillna(0)
    
    # Extract feature dict to return to the backend
    extracted_features = df_processed.iloc[0].to_dict()
    
    # Align features with model (drop target columns if accidentally present)
    cols_to_drop = ["Class", "is_fraud", "is_abuse", "is_bot", "label", "event_type"]
    X = df_processed.drop(columns=[c for c in cols_to_drop if c in df_processed.columns])
    
    ml_score = 0.0
    anomaly_score = 0.0
    
    # 2. Run Main Classification Model
    if fraud_type in _MODELS:
        model_bundle = _MODELS[fraud_type]
        clf = model_bundle["model"]
        
        # Ensure features match
        feature_names = getattr(clf, "feature_names_in_", getattr(clf, "feature_names_", None))
        if feature_names is not None:
            missing_cols = set(feature_names) - set(X.columns)
            for c in missing_cols:
                X[c] = 0
            X = X[feature_names]
            
        if hasattr(clf, "predict_proba"):
            ml_score = float(clf.predict_proba(X)[0][1])
        else:
            ml_score = float(clf.predict(X)[0])
            
        # SHAP Explainability
        try:
            # We use TreeExplainer for Random Forest / XGBoost / CatBoost
            explainer = shap.TreeExplainer(clf)
            shap_values = explainer.shap_values(X)
            
            # Extract top 2 contributing features for this prediction
            if isinstance(shap_values, list): # For some binary classifiers, it returns a list
                shap_vals = shap_values[1][0]
            else:
                shap_vals = shap_values[0]
                
            feature_impacts = zip(X.columns, shap_vals)
            # Sort by absolute impact
            sorted_impacts = sorted(feature_impacts, key=lambda x: abs(x[1]), reverse=True)
            
            for feature, impact in sorted_impacts[:2]:
                if abs(impact) > 0.05: # Only include if it actually had an impact
                    direction = "High" if impact > 0 else "Low"
                    # Translate feature names slightly if needed, or just use raw
                    rule_reasons.append(f"{direction} '{feature}' anomaly detected")
        except Exception as e:
            # Fallback if SHAP fails for any reason
            pass
            
    # 3. Run Anomaly Model (usually for payments)
    if "anomaly" in _MODELS and fraud_type == "payment":
        anomaly_bundle = _MODELS["anomaly"]
        anom_clf = anomaly_bundle["model"]
        
        feature_names_anom = getattr(anom_clf, "feature_names_in_", getattr(anom_clf, "feature_names_", None))
        if feature_names_anom is not None:
            X_anom = X.copy()
            missing_cols = set(feature_names_anom) - set(X_anom.columns)
            for c in missing_cols:
                X_anom[c] = 0
            X_anom = X_anom[feature_names_anom]
            
            # predict returns -1 (anomaly), 1 (normal). Score samples returns negative for anomaly.
            if hasattr(anom_clf, "score_samples"):
                # Normalize raw score roughly between 0 and 1
                raw = anom_clf.score_samples(X_anom)[0]
                # standard isolation forest scores are negative, lower is more anomalous
                anomaly_score = max(0.0, min(1.0, 0.5 - (raw * 2)))
            else:
                pred = anom_clf.predict(X_anom)[0]
                anomaly_score = 1.0 if pred == -1 else 0.0

    # 4. Rule Engine
    rule_score_raw, rule_reasons = evaluate_rules(event_data)
    rule_score_normalized = rule_score_raw / 100.0

    # 5. Ensemble
    final_score = combine_scores(ml_score, anomaly_score, rule_score_normalized)

    # 6. Explainer & Risk Profiling
    explanation = generate_explanation(final_score, rule_reasons, ml_score, anomaly_score)

    # 7. Log for Drift Detection
    log_prediction_distribution(final_score, fraud_type)

    # 8. Construct Final Output (SaaS Format)
    result = {
        "risk_score": explanation["risk_score"],
        "decision": explanation.get("decision", "ALLOW"),
        "fraud_type": f"{fraud_type}_fraud",
        "confidence": explanation["confidence"],
        "reasons": explanation["reasons"],
        
        # Keep old keys for backward compatibility with frontend if needed, but standardize new ones
        "risk_level": explanation["risk_level"],
        "fraud_probability": round(float(final_score), 4),
        "features": extracted_features
    }

    return result

if __name__ == "__main__":
    # Test the inference engine
    test_event = {
        "event_type": "payment",
        "Amount": 6000,
        "country_mismatch": 1,
        "new_device": 1,
        "V1": -2.3, "V2": 1.5, "V3": -1.2, "V4": 3.4, # Mock PCA features
        "transactions_last_1h": 2
    }
    
    print("Testing Central Fraud Intelligence Engine...\n")
    output = predict_transaction(test_event)
    
    import json
    print(json.dumps(output, indent=2))
